### ISSUE TITLE
Intermittent magic_folder.test.test_local_snapshot.LocalSnapshotCreatorTests.test_create_snapshots failure

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#245]
From the NixOS builder on CI:

```
[ERROR]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/nix/store/jw70h4p4hwk7kz6iaa687v5sn25z6hnf-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/nix/store/i2r7a7slgw3300wcvn79bjdczqw83gnd-python2.7-testtools-2.3.0/lib/python2.7/site-packages/testtools/testcase.py", line 719, in _run_test_method
    return self._get_test_method()()
  File "/nix/store/rz6r67ia33vscdq2m1nnvxxx63s4anp4-python2.7-magic-folder-2020-02-05/lib/python2.7/site-packages/magic_folder/test/test_local_snapshot.py", line 236, in test_create_snapshots
    data())
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 974, in wrapped_test
    state.run()
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 695, in run
    info.__expected_traceback,
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 568, in execute
    result = self.test_runner(data, run)
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/executors.py", line 74, in <lambda>
    return lambda data, function: old_school(lambda: function(data))
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/executors.py", line 33, in execute
    return function()
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/executors.py", line 74, in <lambda>
    return lambda data, function: old_school(lambda: function(data))
  File "/nix/store/5w1h6gwajic64alfjkxrsfiwz80q62ga-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 566, in run
    return test(*args, **kwargs)
  File "/nix/store/rz6r67ia33vscdq2m1nnvxxx63s4anp4-python2.7-magic-folder-2020-02-05/lib/python2.7/site-packages/magic_folder/test/test_local_snapshot.py", line 247, in test_create_snapshots
    file.asBytesMode("utf-8").setContent(content)
  File "/nix/store/jw70h4p4hwk7kz6iaa687v5sn25z6hnf-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/python/filepath.py", line 1538, in setContent
    with sib.open('w') as f:
  File "/nix/store/jw70h4p4hwk7kz6iaa687v5sn25z6hnf-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/python/filepath.py", line 1008, in open
    return self.create()
  File "/nix/store/jw70h4p4hwk7kz6iaa687v5sn25z6hnf-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/python/filepath.py", line 1581, in create
    fdint = os.open(self.path, _CREATE_FLAGS)
OSError: [Errno 36] File name too long: '/tmp/nix-build-python2.7-magic-folder-2020-02-05.drv-0/project/_trial_temp/1/magic_folder/test/test_local_snapshot/LocalSnapshotCreatorTests/test_create_snapshots/FgT3OUN1i_n_kidatmp/magic/lfbN7f_DNug8Q67l\xf0\x90\x80\x80.\xf0\x90\x80\x80.\xf0\x90\x80\x80\xf0\x90\x80\x80.\xf0\x9f\x81\x89..\xf0\x9f\x81\x89\xf0\x90\x80\x80.\xf0\x9f\x81\x89\xf0\x90\x80\x80\xf0\x90\x80\x80\xf0\x90\x80\x80..\xf0\x90\x80\x80\xf0\x9f\x81\x89\xf0\x9f\x81\x89\xf0\x90\x80\x80.\xf0\x90\x80\x80\xf0\x90\x80\x80\xf0\x90\x80\x80\xf0\x9d\x9d\x84..\xf0\x90\x80\x80.\xf0\x90\x80\x80\xf0\x9f\x81\x89.\xf0\x90\x80\x80\xf0\x9f\x81\x89\xf0\x90\x80\x80\xf0\x90\x80\x80\xf0\x9f\x81\x89.\xf0\x9f\x81\x89\xf0\x90\x80\x80\xf0\x90\x80\x80\xf0\x90\x80\x80.\xf0\x9f\x81\x890\xf0\x90\x80\x80\xf0\x9d\x9d\x84.\xf0\x9d\x9d\x84\xf0\x90\x80\x80\xf0\x9f\x81\x89\xf0\x9f\x81\x89\xf0\x9f\x81\x89\xf0\x9f\x81\x89.\xf0\x9f\x81\x89\xf0\x9f\x81\x89.\xf0\x90\x80\x80\xf0\x9f\x81\x89\xf0\x90\x80\x80.\xf0\x90\x80\x80\xf0\x9d\x9d\x84\xf0\x90\x80\x800\xf0\x9f\x81\x810.\xf0\x90\x80\x80.new'
```

Looks like the Hypothesis strategy for paths might be generating strings a bit too long.

**Comment by exarkun** [comment]
It's possible those strings are too long but the error here refers to the length of the entire path string so lowering the upper limit on `path_segments()` size is only a bandaid.

The prefix `/tmp/nix-build-python2.7-magic-folder-2020-02-05.drv-0/project/_trial_temp/1/magic_folder/test/test_local_snapshot/LocalSnapshotCreatorTests/test_create_snapshots/FgT3OUN1i_n_kidatmp/magic/` is counted towards the limit as well.

`/tmp/nix-build-python2.7-magic-folder-2020-02-05.drv-0/project/` (63 bytes) is the NixOS contribution to this string.  `_trial_temp/1/magic_folder/test/test_local_snapshot/LocalSnapshotCreatorTests/test_create_snapshots/` is the trial contribution (100 bytes).  `FgT3OUN1i_n_kidatmp/magic/` (26 bytes) is a contribution from the test method itself.  This leaves only 66 bytes for the result from `path_segments`.   Not a lot.  Also in other configurations the prefix could be longer.

This all kinda sucks.  `openat` might be a solution on POSIX but it's only supported in Python 3.3 and newer and so not really accessible to us.  Dramatically lowering the upper bound on `path_segments` might be the only option for the foreseeable future. :/
