### ISSUE TITLE
Intermittent failure of magic_folder.test.test_eliotutil.EliotLoggingTests

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#250]
Both tests on this case fail sometimes:

```
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/tmp/magic-folder.tox/py27-coverage/lib/python2.7/site-packages/magic_folder/test/test_eliotutil.py", line 144, in test_stdlib_event_relayed
    Equals(1),
  File "/tmp/magic-folder.tox/py27-coverage/lib/python2.7/site-packages/testtools/testcase.py", line 502, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 0 != 1: after <built-in function len> on []
```

and

```
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/tmp/magic-folder.tox/py27-coverage/lib/python2.7/site-packages/magic_folder/test/test_eliotutil.py", line 163, in test_twisted_event_relayed
    len, Equals(1),
  File "/tmp/magic-folder.tox/py27-coverage/lib/python2.7/site-packages/testtools/testcase.py", line 502, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 0 != 1: after <built-in function len> on []
```

**Comment by exarkun** [comment]
These also come after a timeout of `magic_folder.test.cli.test_magic_folder.CreateMagicFolder.test_leave_no_folders_at_all`, not sure if that's related somehow.
