### ISSUE TITLE
The "create snapshot" endpoint hangs if no file exists at the specified path

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#283]
The Eliot log contains

```
66cb664c-886f-462c-9b9a-cab66f309496
└── magic-folder:local-snapshot-creator:process-queue/1 ⇒ started 2020-08-31 14:48:25Z ⧖ 0.000s
    ├── relpath: /run/user/1000/mfjunk/magic/foo
    └── magic-folder:local-snapshot-creator:process-queue/2 ⇒ failed 2020-08-31 14:48:25Z
        ├── errno: 2
        ├── exception: exceptions.IOError
        └── reason: [Errno 2] No such file or directory: u'/run/user/1000/mfjunk/magic/foo'

e360e93c-2cc9-4bf3-811e-f8949d9f66ff
└── eliot:traceback/1 2020-08-31 14:48:25Z
    ├── errno: 2
    ├── exception: exceptions.IOError
    ├── reason: [Errno 2] No such file or directory: u'/run/user/1000/mfjunk/magic/foo'
    └── traceback: Traceback (most recent call last):⏎
          File "/home/exarkun/Work/python/magic-folder/src/magic_folder/magic_folder.py", line 819, in _process_queue⏎
          File "/home/exarkun/Scratch/magic-folder/lib/python2.7/site-packages/eliot/_generators.py", line 160, in wrapper⏎
        IOError: [Errno 2] No such file or directory: u'/run/user/1000/mfjunk/magic/foo'⏎
        

3d527a83-8d6e-4441-be6e-cbf1be53c31b
└── magic-folder:local-snapshots:add-file/1 ⇒ started 2020-08-31 14:48:25Z
```

and the request hangs indefinitely.

**Comment by meejah** [comment]
It now reports an error properly.
