### ISSUE TITLE
PR #502 breaks "file-status" HTTP API with "sqlite3.OperationalError: no such column: last_updated_ns"

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#505]
Upon updating and testing Magic-Folder after #502 (c5760cd619370ee6b67f37c7f5c85fa75c07138c), I observe an unhandled exception (spewed to `magic-folder run`'s stdout) and an HTTP 500 error when requesting a `GET  /v1/magic-folder/<folder-name>/file-status` as follows:

```
Traceback (most recent call last):
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1242, in consumeData
     self.processHandshake()
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 2856, in processHandshake
     txaio.add_callbacks(f, self.succeedHandshake, forward_error)
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/txaio/tx.py", line 506, in add_callbacks
     future.addCallbacks(callback, errback)
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
     self._runCallbacks()
 --- <exception caught here> ---
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 3049, in succeedHandshake
     self._onOpen()
   File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 301, in _onOpen
     self.onOpen()
   File "/home/user/code/magic-folder/src/magic_folder/status.py", line 107, in onOpen
     self.status.client_connected(self)
   File "/home/user/code/magic-folder/src/magic_folder/status.py", line 233, in client_connected
     self._last_state = self._marshal_state()
   File "/home/user/code/magic-folder/src/magic_folder/status.py", line 285, in _marshal_state
     for name in self._config.list_magic_folders()
   File "/home/user/code/magic-folder/src/magic_folder/status.py", line 285, in <dictcomp>
     for name in self._config.list_magic_folders()
   File "/home/user/code/magic-folder/src/magic_folder/status.py", line 268, in folder_data_for
     in self._config.get_magic_folder(name).get_recent_remotesnapshot_paths(30)
   File "/home/user/code/magic-folder/src/magic_folder/config.py", line 460, in with_cursor
     return f(self, cursor, *a, **kw)
   File "/home/user/code/magic-folder/src/magic_folder/config.py", line 1118, in get_recent_remotesnapshot_paths
     """
 sqlite3.OperationalError: no such column: last_updated_ns
```

**Comment by crwood** [comment]
Further investigation shows that this was caused by having an old (pre-#502) magic-folder database; newly created (post-#502) magic-folder databases do not throw this exception.
