### ISSUE TITLE
`magic-folder migrate` fails with TypeError: 'name' must be <type 'unicode'>

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#509]
With current magic-folder (776c36ff70d5207353303e0423d6de4f1ac4bbd4), the `magic-folder migrate` subcommand fails as follows (using `magic-folder --debug migrate --node-directory=/home/user/.tahoe --listen-endpoint=tcp:4321 --author=Bob`):

```
main function encountered error
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/code/magic-folder/src/magic_folder/cli.py", line 692, in run_magic_folder_options
    yield f(so)
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/home/user/code/magic-folder/src/magic_folder/cli.py", line 692, in run_magic_folder_options
    yield f(so)
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/eliot/_generators.py", line 139, in wrapper
    value_out = gen.send(value_in)
  File "/home/user/code/magic-folder/src/magic_folder/cli.py", line 227, in migrate
    options['client-endpoint'],
  File "/home/user/code/magic-folder/src/magic_folder/migrate.py", line 76, in magic_folder_migrate
    author = create_local_author(author_name)
  File "/home/user/code/magic-folder/src/magic_folder/snapshot.py", line 123, in create_local_author
    signing_key,
  File "<attrs generated init magic_folder.snapshot.LocalAuthor>", line 5, in __init__
    __attr_validator_name(self, __attr_name, self.name)
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/attr/_make.py", line 2146, in __call__
    v(inst, attr, value)
  File "/home/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/attr/validators.py", line 45, in __call__
    value,
exceptions.TypeError: ("'name' must be <type 'unicode'> (got 'Bob' that is a <type 'str'>).", Attribute(name='name', default=NOTHING, validator=_AndValidator(_validators=(<instance_of validator for type <type 'unicode'>>,)), repr=True, eq=True, order=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None, kw_only=False), <type 'unicode'>, 'Bob')
```

**Comment by meejah** [comment]
fixed via python3 port
