### ISSUE TITLE
Flaky test: magic_folder.test.test_status.StatusTests.test_unknown_magic_folder_name

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#80]
```
Traceback (most recent call last):
  File "/home/meejah/work/leastauthority/src/magic-folder/venv/local/lib/python2.7/site-packages/twisted/internet/defer
.py", line 151, in maybeDeferred
    result = f(*args, **kw)                                                                                           
  File "/home/meejah/work/leastauthority/src/magic-folder/venv/local/lib/python2.7/site-packages/testtools/testcase.py"
, line 723, in _run_test_method                                                                                            return self._get_test_method()()                                                                                     File "/home/meejah/work/leastauthority/src/magic-folder/src/magic_folder/test/test_status.py", line 133, in test_unkn
own_magic_folder_name
    folder_names(),
  File "/home/meejah/work/leastauthority/src/magic-folder/venv/local/lib/python2.7/site-packages/hypothesis/core.py", l
ine 1071, in wrapped_test                                                                                             
    state.run_engine()
  File "/home/meejah/work/leastauthority/src/magic-folder/venv/local/lib/python2.7/site-packages/hypothesis/core.py", l
ine 789, in run_engine
    info.__expected_traceback,                             
  File "/home/meejah/work/leastauthority/src/magic-folder/venv/local/lib/python2.7/site-packages/hypothesis/core.py", line 656, in execute_once                                                                                               
    % (test.__name__, text_repr[0])                         
  File "/home/meejah/work/leastauthority/src/magic-folder/venv/local/lib/python2.7/site-packages/hypothesis/core.py", line 856, in __flaky
    raise Flaky(message)                                                       
hypothesis.errors.Flaky: Hypothesis test_unknown_magic_folder_name(self=<magic_folder.test.test_status.StatusTests.test_unknown_magic_folder_name id=0x7f024dca7e50>, folder_names=[u'\x0e\U000aea6e\x1d',                                   
 u'\U000cd527\x05',                                                    
 u'\U0003b33c&\u4bbe',
 u'\x07\x02\U000c4c63\x08',
 u'\U00087e93',                   
 u'\x17\U00038411',                                                                                                    
 u'\U0007195e+',                
 u'\U00015a2f\U000e8997\x02 \U001089eb\r\U0002b815#\U0008c5c4\u6588\U00077492\U000f2fcd\x03',                         
 u'%',                                                                                                                 
 u'\ue70f\n\x14\U000ba7d6\U000b9f5d("\ud428'], collective_dircap=u'URI:DIR2:fdis5qniqxtadltxmcnd6ta7im:3mvag25uktenhbb466jtqtediw67pdldynnhwvogxqpjqlte5kdq', upload_dircap=u'URI:DIR2:jul3r6faef4hnqc7n4mkszakdy:t33i2ahnpcsl6f67udrb5rwsw74h2tqzcxcma744hyz4cuanhdrq') produces unreliable results: Falsified on the first call but did not on a subsequent one    
```

**Comment by meejah** [comment]
I can repeat this locally fairly quickly using: `python -m twisted.trial -x -u magic_folder.test.test_status.StatusTests.test_unknown_magic_folder_name`

**Comment by vu3rdd** [comment]
I saw this a couple of times too on CI yesterday.

**Comment by meejah** [comment]
No longer relevant.
